# Generated by Django 3.1.3 on 2023-01-02 18:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='correct',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='id_question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='question',
            name='id_course',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlinecourse.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='courses',
            field=models.ManyToManyField(to='onlinecourse.Course'),
        ),
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='This is a sample question.', max_length=500),
        ),
        migrations.AddField(
            model_name='submission',
            name='date_submitted',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='total_learners',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='learner',
            name='social_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(default='Lesson number X', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
